# Generated by Django 5.2.6 on 2026-07-30 11:06

import django.db.models.deletion
import rooms.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('code', models.CharField(default=rooms.models.room_code, editable=False, max_length=6, unique=True)),
                ('password_hash', models.CharField(blank=True, max_length=128)),
                ('max_players', models.PositiveSmallIntegerField(default=10)),
                ('starting_zombies', models.PositiveSmallIntegerField(default=1)),
                ('duration_minutes', models.PositiveSmallIntegerField(default=60)),
                ('status', models.CharField(choices=[('lobby', 'Лобби'), ('playing', 'Игра'), ('finished', 'Завершена')], default='lobby', max_length=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('organizer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='organized_rooms', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='RoomPlayer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ready', models.BooleanField(default=False)),
                ('current_role', models.CharField(blank=True, choices=[('survivor', 'Выживший'), ('soldier', 'Солдат'), ('doctor', 'Доктор'), ('zombie', 'Зомби')], max_length=12)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='rooms.room')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='room_memberships', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='room',
            name='players',
            field=models.ManyToManyField(related_name='rooms', through='rooms.RoomPlayer', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='roomplayer',
            constraint=models.UniqueConstraint(fields=('room', 'user'), name='unique_room_member'),
        ),
    ]
