# Generated by Django 5.2.6 on 2026-07-30 11:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('rooms', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('map_name', models.CharField(default='Нурсая', max_length=40)),
                ('status', models.CharField(choices=[('running', 'Идёт'), ('stopped', 'Остановлена'), ('finished', 'Завершена')], default='running', max_length=12)),
                ('winner', models.CharField(choices=[('survivors', 'Выжившие'), ('zombies', 'Зомби'), ('none', 'Нет')], default='none', max_length=12)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('ends_at', models.DateTimeField()),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('map_data', models.JSONField(blank=True, default=dict)),
                ('room', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='game', to='rooms.room')),
            ],
        ),
        migrations.CreateModel(
            name='GameEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=32)),
                ('message', models.CharField(max_length=250)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='game.game')),
            ],
        ),
    ]
